[pre-commit]
parallel = true

# Rust
[[pre-commit.jobs]]
name = "cargo-fmt"
glob = "src/rust/**/*.rs"
run = "cd src/rust && cargo fmt"
stage_fixed = true

[[pre-commit.jobs]]
name = "cargo-clippy"
glob = "src/rust/**/*.rs"
run = "cd src/rust && cargo clippy -- -D warnings"

# Web
[[pre-commit.jobs]]
name = "oxlint-web"
glob = "src/web/**/*.{ts,vue}"
run = "bunx oxlint --config src/web/.oxlintrc.json {staged_files} --fix"
stage_fixed = true

[[pre-commit.jobs]]
name = "oxfmt-web"
glob = "src/web/**/*.{ts,vue}"
run = "bunx oxfmt {staged_files}"
stage_fixed = true
